name: ci

on:
  push:
    branches:
      - develop
      - rc
      - stable
  pull_request:
    branches:
      - develop
      - rc
      - stable
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: pnpm

      - name: preparing .env ⏚
        run: cp .env.example .env && cp env.example.ts env.ts

      - name: install dependencies 🎁
        run: pnpm install

      - name: type check ⚙️
        run: pnpm run typecheck

      - name: Run linter 👀
        run: pnpm run lint

      - name: Test build 👀
        run: pnpm run build
